package xo;

public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    public static void main(String[] args) {
        Main $Main = new Main();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        $icon9 = new javax.swing.JLabel();
        $icon8 = new javax.swing.JLabel();
        $icon7 = new javax.swing.JLabel();
        $icon4 = new javax.swing.JLabel();
        $icon5 = new javax.swing.JLabel();
        $icon6 = new javax.swing.JLabel();
        $icon3 = new javax.swing.JLabel();
        $icon1 = new javax.swing.JLabel();
        $icon2 = new javax.swing.JLabel();
        $bgBoard = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setLayout(null);

        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(553, 258, 47, 17);

        jLabel12.setText("jLabel12");
        add(jLabel12);
        jLabel12.setBounds(655, 258, 47, 17);

        jLabel13.setText("jLabel13");
        add(jLabel13);
        jLabel13.setBounds(529, 380, 47, 17);

        jLabel14.setText("jLabel14");
        add(jLabel14);
        jLabel14.setBounds(606, 380, 47, 17);

        $icon9.setText("icon9");
        add($icon9);
        $icon9.setBounds(340, 340, 160, 160);

        $icon8.setText("icon8");
        add($icon8);
        $icon8.setBounds(170, 340, 160, 160);

        $icon7.setText("icon7");
        add($icon7);
        $icon7.setBounds(0, 340, 160, 160);

        $icon4.setText("icon4");
        add($icon4);
        $icon4.setBounds(0, 170, 160, 160);

        $icon5.setText("icon5");
        add($icon5);
        $icon5.setBounds(170, 170, 160, 160);

        $icon6.setText("icon6");
        add($icon6);
        $icon6.setBounds(340, 170, 160, 160);

        $icon3.setText("icon3");
        add($icon3);
        $icon3.setBounds(340, 0, 160, 160);

        $icon1.setText("icon1");
        add($icon1);
        $icon1.setBounds(0, 0, 160, 160);

        $icon2.setText("icon2");
        add($icon2);
        $icon2.setBounds(170, 0, 160, 160);

        $bgBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xo/image/board.png"))); // NOI18N
        add($bgBoard);
        $bgBoard.setBounds(0, 0, 499, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $bgBoard;
    private javax.swing.JLabel $icon1;
    private javax.swing.JLabel $icon2;
    private javax.swing.JLabel $icon3;
    private javax.swing.JLabel $icon4;
    private javax.swing.JLabel $icon5;
    private javax.swing.JLabel $icon6;
    private javax.swing.JLabel $icon7;
    private javax.swing.JLabel $icon8;
    private javax.swing.JLabel $icon9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    // End of variables declaration//GEN-END:variables
}
